//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanVeMay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANGTRATHONGTINVE
    {
        public int LICHTRINHBAYID { get; set; }
        public int LOAIVEID { get; set; }
        public double GIAVE { get; set; }
        public int SOLUONGMAX { get; set; }
        public int GHETRONG { get; set; }
    
        public virtual LICHTRINHBAY LICHTRINHBAY { get; set; }
        public virtual LOAIVE LOAIVE { get; set; }
    }
}
