//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBanVeMay.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public int SLSB { get; set; }
        public double MIN_TGB { get; set; }
        public double MIN_TGD { get; set; }
        public double MAX_TGD { get; set; }
        public int SLHV { get; set; }
        public double MIN_TGDV { get; set; }
        public double MIN_TGHV { get; set; }
        public int ID { get; set; }
    }
}
